Repository xorbitsai/xorbits, pull requests merged in 2022-12, with the labels that each got.

#76 Enh: manual execution
  benchmarks/tpch/run_queries.py
  python/xorbits/__init__.py
  python/xorbits/core/__init__.py
  python/xorbits/core/adapter.py
  python/xorbits/core/data.py
  python/xorbits/core/execution.py
  python/xorbits/core/tests/test_execution.py
Labels: enhancement

#79 doc: Added index doc
  README.md
  doc/source/index.rst
Labels: documentation

#68 enh: Implements `__instancecheck__` for `DataRefMeta`
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_instance_check.py
  python/xorbits/core/utils/docstring.py
  python/xorbits/core/utils/tests/test_docstring.py
  python/xorbits/numpy/core.py
  python/xorbits/numpy/lib/index_tricks.py
  python/xorbits/numpy/mars_adapters/flatiter.py
  python/xorbits/numpy/mars_adapters/tests/test_mars_adapters.py
  python/xorbits/pandas/core.py
  python/xorbits/pandas/groupby.py
  python/xorbits/pandas/mars_adapters/tests/test_pandas_examples.py
  python/xorbits/remote/mars_adapters/tests/test_mars_adapters.py
Labels: enhancement

#84 doc: Add social media links
  doc/source/conf.py
Labels: documentation

#87 DOC: Add roadmaps to README.md
  README.md
  doc/source/index.rst
Labels: documentation

#81 Enh: execute when export methods being called
  python/xorbits/core/adapter.py
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_instance_check.py
  python/xorbits/pandas/mars_adapters/__init__.py
  python/xorbits/pandas/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/tests/test_execution.py
  python/xorbits/pandas/pandas_adapters/core.py
  python/xorbits/pandas/tests/test_accessors.py
Labels: enhancement

#89 DOC: Add xorbits API
  README.md
  doc/source/reference/index.rst
  doc/source/reference/xorbits/index.rst
  python/xorbits/deploy/__init__.py
Labels: documentation

#90 ENH: Fix some coverage issues
  python/xorbits/core/adapter.py
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_adapter.py
  python/xorbits/core/tests/test_instance_check.py
  python/xorbits/core/utils/docstring.py
  python/xorbits/numpy/mars_adapters/tests/test_mars_adapters.py
  python/xorbits/pandas/__init__.py
  python/xorbits/pandas/groupby.py
  python/xorbits/pandas/mars_adapters/core.py
Labels: enhancement

#88 ENH: Handle inference failure for user defined functions
  python/xorbits/core/adapter.py
  python/xorbits/numpy/mars_adapters/__init__.py
  python/xorbits/pandas/mars_adapters/__init__.py
  python/xorbits/pandas/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/tests/test_user_defined_functions.py
Labels: enhancement

#94 DOC: xorbits.numpy getting started
  doc/source/getting_started/index.rst
  doc/source/getting_started/numpy.rst
  doc/source/index.rst
Labels: documentation

#105 DOC: pandas getting started
  doc/source/getting_started/index.rst
  doc/source/getting_started/pandas.rst
Labels: documentation

#100 DOC: Add warnings for methods falling back to pandas
  python/xorbits/core/utils/docstring.py
  python/xorbits/core/utils/tests/test_docstring.py
  python/xorbits/pandas/pandas_adapters/core.py
Labels: documentation, enhancement

#102 TST: Use checked session in test fixtures
  python/xorbits/conftest.py
  python/xorbits/core/adapter.py
  python/xorbits/pandas/mars_adapters/tests/test_user_defined_functions.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
  python/xorbits/tests/core.py
  python/xorbits/tests/test_config.yml
Labels: enhancement, testing

#112 BUG: Remove imports from test module
  python/xorbits/core/adapter.py
  python/xorbits/tests/core.py
Labels: bug

#106 BUG: PlotAccessor.__call__ is not implemented
  doc/source/_templates/autosummary/accessor_callable.rst
  python/xorbits/pandas/plotting.py
Labels: bug

#120 ENH: Suppress Numpy warnings
  python/xorbits/numpy/__init__.py
  python/xorbits/web/tests/test_request_web.py
Labels: enhancement

#114 DOC: installation
  doc/source/getting_started/index.rst
  doc/source/getting_started/installation.rst
Labels: documentation

#118 ENH: Make Xorbits Data iterable
  .github/workflows/python.yaml
  python/xorbits/core/adapter.py
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_adapter.py
  python/xorbits/core/tests/test_execution.py
  python/xorbits/pandas/mars_adapters/__init__.py
  python/xorbits/pandas/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/tests/test_execution.py
  python/xorbits/web/tests/test_request_web.py
Labels: enhancement

#122 DOC: add deployment doc
  README.md
  doc/source/deployment/cluster.rst
  doc/source/deployment/index.rst
  doc/source/deployment/local.rst
  doc/source/getting_started/installation.rst
  doc/source/index.rst
Labels: documentation

#124 BUG: Add cls method fallback warning
  python/xorbits/pandas/pandas_adapters/core.py
Labels: bug

#116 BUG: handle at and iloc
  python/xorbits/core/adapter.py
  python/xorbits/numpy/lib/index_tricks.py
  python/xorbits/numpy/mars_adapters/core.py
  python/xorbits/pandas/accessors.py
  python/xorbits/pandas/core.py
  python/xorbits/pandas/indexing.py
  python/xorbits/pandas/mars_adapters/__init__.py
  python/xorbits/pandas/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/loc.py
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
  python/xorbits/pandas/plotting.py
  python/xorbits/pandas/tests/test_accessors.py
  python/xorbits/pandas/window.py
Labels: bug

#125 TST: enhance tests stability
  README.md
  python/xorbits/conftest.py
  python/xorbits/web/tests/test_request_web.py
Labels: testing

#126 ENH: version disclaimers
  python/xorbits/core/utils/docstring.py
  python/xorbits/core/utils/tests/test_docstring.py
Labels: documentation

#127 ENH: Create mergify configuration
  .github/mergify.yml
Labels: enhancement
