Repository xorbitsai/xorbits, pull requests merged in 2023-02, with the labels that each got.

#181 DOC: Translate part of deployment documentations into zh_CN
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/cluster.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/local.po
Labels: documentation

#184 DOC: Fix ref link in deployment section
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/cluster.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/local.po
Labels: documentation

#170 BLD: Docker image supports multi python versions
  .github/workflows/docker-cd.yaml
  .github/workflows/kubernetes.yaml
  doc/source/deployment/kubernetes.rst
  python/xorbits/deploy/docker/Dockerfile
  python/xorbits/deploy/docker/Dockerfile.base
  python/xorbits/deploy/kubernetes/config.py
  python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
  python/xorbits/deploy/kubernetes/worker.py
  python/xorbits/pandas/pandas_adapters/core.py
Labels: build

#185 DOC: zh_CN for Installation
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  python/setup.cfg
Labels: documentation

#186 Doc: User guide
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deferred_execution.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/index.po
Labels: documentation

#190 DOC: Translate Kubernetes deployment docs
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/cloud.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/kubernetes.po
Labels: documentation

#194 DOC: fix links for README
  README.md
  doc/source/getting_started/installation.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/deployment.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: documentation

#197 DOC: add links for index doc
  doc/source/conf.py
  doc/source/development/contributing.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: documentation

#201 DOC: Add twitter link to README.md
  README.md
Labels: documentation

#200 TST: Add asv benchmarks
  .github/workflows/asv.yaml
  asv/asv.conf.json
  asv/benchmarks/__init__.py
  asv/benchmarks/empty_remotes.py
  asv/benchmarks/execution.py
  asv/benchmarks/graph_assigner.py
  asv/benchmarks/graph_builder.py
  asv/benchmarks/import.py
  asv/benchmarks/learn/__init__.py
  asv/benchmarks/learn/metrics.py
  asv/benchmarks/learn/model_selection.py
  asv/benchmarks/serialize.py
  asv/benchmarks/storage.py
  asv/benchmarks/util_tokenize.py
  python/xorbits/_mars/tensor/__init__.py
Labels: testing

#205 BUG: group dataframe by anonymous series
  python/xorbits/_mars/optimization/logical/tileable/__init__.py
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/input_column_selector.py
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_input_column_selector.py
Labels: bug

#217 ENH: execute refs in user ns eagerly
  python/setup.cfg
  python/xorbits/core/execution.py
  python/xorbits/core/tests/test_execution.py
Labels: enhancement

#219 TST: Add checks for _mars module
  .github/workflows/python.yaml
  python/setup.cfg
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/self_column_selector.py
  python/xorbits/_mars/tensor/special/err_fresnel.py
Labels: testing

#218 ENH: Support `read_csv` with passing `skiprows`
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: enhancement

#224 DOC: update benchmark links
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: documentation

#223 BUG: Fix wrong length of DataFrame
  .github/workflows/python.yaml
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_execution.py
  python/xorbits/numpy/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
Labels: bug

#230 CLN: Remove `_is_exiting_future`
  python/xorbits/_mars/deploy/oscar/local.py
Labels: enhancement

#239 CLN: Remove code related to caching function
  python/xorbits/_mars/dataframe/base/apply.py
  python/xorbits/_mars/dataframe/base/map_chunk.py
  python/xorbits/_mars/dataframe/groupby/apply.py
  python/xorbits/_mars/dataframe/tests/test_utils.py
  python/xorbits/_mars/dataframe/utils.py
  python/xorbits/_mars/deploy/oscar/tests/test_clean_up_and_restore_func.py
  python/xorbits/_mars/utils.py
Labels: enhancement

#240 TST: GPU CI
  .github/workflows/gpu-ci.yaml
Labels: testing

#241 BUG: add sleep when waiting for endpoint ready in K8s
  python/xorbits/deploy/kubernetes/client.py
  python/xorbits/deploy/kubernetes/config.py
Labels: bug
