Repository xorbitsai/xorbits, pull requests merged in 2023-08, with the labels that each got.

#633 BUG: Fix Huggingface dataset loader filelock conflict
  doc/source/libraries/xorbits_data/datasets.rst
  python/xorbits/_mars/learn/contrib/lightgbm/classifier.py
  python/xorbits/_mars/learn/contrib/lightgbm/ranker.py
  python/xorbits/_mars/learn/contrib/lightgbm/regressor.py
  python/xorbits/_mars/learn/contrib/xgboost/classifier.py
  python/xorbits/_mars/learn/contrib/xgboost/core.py
  python/xorbits/_mars/learn/contrib/xgboost/regressor.py
  python/xorbits/_mars/lib/mkl_interface.py
  python/xorbits/datasets/backends/huggingface/loader.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
Labels: bug

#622 BUG: Fix pre-commit arg and CI node version
  .github/workflows/python.yaml
  .pre-commit-config.yaml
  python/xorbits/_mars/_version.py
  python/xorbits/_mars/learn/cluster/_k_means_elkan.pyx
  python/xorbits/_mars/learn/cluster/_k_means_fast.pxd
  python/xorbits/_mars/learn/cluster/_k_means_fast.pyx
  python/xorbits/_mars/learn/cluster/_k_means_lloyd.pyx
  python/xorbits/_mars/learn/utils/_cython_blas.pyx
  python/xorbits/_mars/lib/ordered_set.pyx
  python/xorbits/_mars/services/web/index.html
  python/xorbits/web/ui/index.html
  python/xorbits/web/ui/package-lock.json
  python/xorbits/web/ui/package.json
  python/xorbits/web/ui/resources/favicon.svg
Labels: bug

#639 FEAT: Export dataset
  .github/workflows/python.yaml
  doc/source/reference/datasets/dataset.rst
  python/setup.cfg
  python/xorbits/datasets/backends/huggingface/core.py
  python/xorbits/datasets/backends/huggingface/export.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
  python/xorbits/datasets/dataset.py
Labels: feature

#641 BUG: Fix missing ArrowDtype
  .github/workflows/python.yaml
  python/setup.cfg
  python/xorbits/datasets/__init__.py
  python/xorbits/datasets/adapter.py
  python/xorbits/datasets/backends/huggingface/__init__.py
  python/xorbits/datasets/backends/huggingface/core.py
  python/xorbits/datasets/backends/huggingface/from_huggingface.py
  python/xorbits/datasets/backends/huggingface/loader.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
  python/xorbits/pandas/__init__.py
Labels: bug

#642 BLD: fix docker build on python 3.11
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#644 BLD: add datasets dependency in docker base image
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#645 BUG: Fix `_generate_value` when building mock dataframe
  python/xorbits/_mars/dataframe/tests/test_utils.py
  python/xorbits/_mars/dataframe/utils.py
Labels: bug

#647 BUG: Fix issues when connecting to a real yarn cluster
  python/xorbits/_mars/deploy/yarn/supervisor.py
  python/xorbits/_mars/deploy/yarn/worker.py
Labels: bug

#643 FEAT: Iterable dataset
  .github/workflows/python.yaml
  python/xorbits/datasets/backends/huggingface/export.py
  python/xorbits/datasets/iterable_dataset.py
  python/xorbits/datasets/tests/__init__.py
  python/xorbits/datasets/tests/test_iterable_dataset.py
Labels: feature

#646 TST: K8s with juicefs CI may leads to pv conflict
  python/xorbits/deploy/kubernetes/client.py
  python/xorbits/deploy/kubernetes/external_storage/juicefs/config.py
Labels: testing

#648 ENH: Compatible with scikit-learn 1.3.0
  .github/workflows/python.yaml
  python/xorbits/_mars/learn/cluster/_k_means_init.py
  python/xorbits/_mars/learn/cluster/_kmeans.py
  python/xorbits/_mars/learn/cluster/tests/test_k_means.py
  python/xorbits/_mars/learn/datasets/tests/test_samples_generator.py
  python/xorbits/_mars/learn/decomposition/tests/test_pca.py
  python/xorbits/_mars/learn/decomposition/tests/test_truncated_svd.py
  python/xorbits/_mars/learn/metrics/tests/test_classification.py
  python/xorbits/_mars/learn/metrics/tests/test_ranking.py
  python/xorbits/_mars/learn/metrics/tests/test_regression.py
  python/xorbits/_mars/learn/neighbors/base.py
  python/xorbits/_mars/learn/preprocessing/tests/test_data.py
  python/xorbits/_mars/learn/semi_supervised/tests/test_label_propagation.py
  python/xorbits/_mars/learn/utils/core.py
  python/xorbits/_mars/learn/utils/tests/test_multiclass.py
  python/xorbits/_mars/learn/utils/tests/test_validation.py
Labels: enhancement

#656 TST: Add test_put_get_arrow
  python/xorbits/_mars/storage/tests/test_libs.py
Labels: testing

#668 BUG: Fix dtypes of `pd.pivot_table`
  python/xorbits/_mars/dataframe/base/pivot_table.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
Labels: bug

#670 BUG: Fix tpch
  benchmarks/tpch/run_queries.py
Labels: bug

#674 FEAT: MMAP storage backend
  python/xorbits/_mars/deploy/oscar/local.py
  python/xorbits/_mars/storage/__init__.py
  python/xorbits/_mars/storage/mmap.py
  python/xorbits/_mars/storage/tests/test_libs.py
  python/xorbits/_mars/tests/test_session.py
  python/xorbits/deploy/__init__.py
  python/xorbits/deploy/tests/test_deploy.py
Labels: feature
