Repository xorbitsai/xorbits, pull requests merged in 2023-01, with the labels that each got.

#134 ENH: replace head2head compare about API with gif for readme
  README.md
  doc/source/_static/pandas_vs_xorbits.gif
Labels: enhancement

#135 DOC: Added API implemented version and plan
  README.md
  doc/source/index.rst
Labels: documentation

#131 DOC: documents about K8s deployment
  README.md
  doc/source/deployment/cloud.rst
  doc/source/deployment/index.rst
  doc/source/deployment/kubernetes.rst
  doc/source/reference/xorbits/index.rst
  python/xorbits/deploy/kubernetes/client.py
  python/xorbits/deploy/kubernetes/tests/test_config.py
Labels: documentation

#137 TST: Add codecov configuration
  .github/codecov.yml
  .github/workflows/kubernetes.yaml
  .github/workflows/python.yaml
Labels: testing

#136 DOC: Added benchmark for readme & doc index
  README.md
  doc/source/index.rst
Labels: documentation

#140 CHORE: Update pandas_vs_xorbits.gif
  doc/source/_static/pandas_vs_xorbits.gif
Labels: documentation

#141 ENH: Stop executing DataRef when pycharm etc tries to evaluate properties in debug
  python/xorbits/core/data.py
  python/xorbits/tests/mock_pydevd_xml.py
  python/xorbits/tests/test_utils.py
  python/xorbits/utils.py
Labels: enhancement

#145 DOC: refine README and doc index
  README.md
  doc/source/index.rst
Labels: documentation

#149 TST: Fix test_cluster hanging
  python/xorbits/tests/test_cluster.py
Labels: testing

#154 DOC: Use one supervisoras example for cluster deployment
  doc/source/deployment/cluster.rst
  python/xorbits/tests/test_cluster.py
Labels: documentation

#150 ENH: Make sure only one local cluster exists
  python/xorbits/deploy/__init__.py
  python/xorbits/deploy/tests/test_deploy.py
Labels: enhancement

#155 ENH: K8s deployment supports installing pip and conda packages
  .github/workflows/kubernetes.yaml
  doc/source/deployment/cloud.rst
  doc/source/deployment/kubernetes.rst
  python/xorbits/deploy/__init__.py
  python/xorbits/deploy/docker/Dockerfile
  python/xorbits/deploy/docker/install.sh
  python/xorbits/deploy/kubernetes/client.py
  python/xorbits/deploy/kubernetes/config.py
  python/xorbits/deploy/kubernetes/tests/test_config.py
  python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
Labels: enhancement

#161 DOC: Add i18n support
  doc/source/conf.py
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/cloud.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/cluster.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/kubernetes.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/local.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/numpy.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/pandas.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/array-creation.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/array-manipulation.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/bitwise.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/fft.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/indexing.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/io.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/linalg.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/logic.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/math.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/random.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/set.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/sort.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/statistics.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/frame.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/general_functions.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/groupby.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/indexing.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/io.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/series.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/window.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/xorbits/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deferred_execution.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/index.po
Labels: documentation

#164 ENH: Support aws and azure install options
  python/setup.cfg
Labels: enhancement

#167 Fix: change slack link
  README.md
  doc/source/index.rst
Labels: bug

#168 BUG: fix all the slack links
  README.md
  doc/source/conf.py
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: bug

#171 BUG: update slack links
  README.md
  doc/source/conf.py
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: bug

#172 BUG: Incompatible versions of Minikube and Kubernetes
  .github/workflows/kubernetes.yaml
Labels: bug

#176 DOC: Add note about installing requirements for ```10 minutes to xorbits.numpy```
  doc/source/getting_started/numpy.rst
Labels: documentation

#178 DOC: fix index and update po
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/cloud.po
  doc/source/locale/zh_CN/LC_MESSAGES/deployment/kubernetes.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/numpy.po
Labels: documentation

#179 DOC: add `make html_zh_cn`
  README.md
  doc/Makefile
  doc/make.bat
  doc/requirements-doc.txt
  doc/source/index.rst
  doc/source/norm_zh.py
Labels: documentation

#177 BUG: Workers pod may turn to running status before supervisor
  python/xorbits/deploy/kubernetes/client.py
  python/xorbits/deploy/kubernetes/config.py
  python/xorbits/deploy/kubernetes/tests/test_config.py
Labels: bug

#180 DOC: add zh_CN translation for index
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: documentation
