Repository xorbitsai/xorbits, pull requests merged in 2023-06, with the labels that each got.

#484 BUG: fix read pickle bug and add UT
  python/xorbits/pandas/pandas_adapters/core.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Labels: bug

#485 ENH: update pivot_table op
  python/xorbits/_mars/dataframe/base/pivot_table.py
Labels: enhancement

#477 FEAT: create gpu feature on dashboard
  python/xorbits/_mars/services/cluster/gather.py
  python/xorbits/web/ui/src/Dashboard.js
  python/xorbits/web/ui/src/node_info/NodeResourceTab.js
  python/xorbits/web/ui/src/node_info/SupervisorDetailPage.js
  python/xorbits/web/ui/src/node_info/WorkerDetailPage.js
Labels: feature, gpu

#486 ENH: update tokenizing numpy
  python/xorbits/_mars/_utils.pyx
Labels: enhancement

#483 ENH: update pivot op
  python/xorbits/_mars/dataframe/base/pivot.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
Labels: enhancement

#496 BUG: fix sort_index bug when level attribute is None
  python/xorbits/_mars/dataframe/sort/sort_index.py
  python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
Labels: bug

#495 DOC: Update Xorbits build and installation process
  doc/source/development/contributing_environment.rst
Labels: documentation

#490 BUG: Try to fix UCX communication backend argument parser
  python/xorbits/_mars/deploy/oscar/cmdline.py
  python/xorbits/_mars/deploy/oscar/supervisor.py
  python/xorbits/_mars/deploy/oscar/worker.py
Labels: bug

#508 DOC: Adds guide to use `-f` flag to modify default config.
  doc/source/user_guide/deployment_cluster.rst
Labels: documentation

#512 BUG: Fix the GPU display issue in worker and dashboard page
  python/xorbits/_mars/dataframe/groupby/apply.py
  python/xorbits/_mars/services/cluster/gather.py
Labels: bug, gpu

#498 BUG: Fix errors for WSL machines with GPU.
  python/xorbits/_mars/lib/nvutils.py
  python/xorbits/_mars/resource.py
Labels: bug, gpu

#514 ENH: Make memory allocation more aggressive on local
  python/xorbits/_mars/deploy/oscar/local.py
  python/xorbits/_mars/services/scheduling/worker/quota.py
Labels: enhancement

#502 FEAT: Support xgboost wrapper
  .github/workflows/python.yaml
  python/xorbits/core/adapter.py
  python/xorbits/xgboost/__init__.py
  python/xorbits/xgboost/mars_adapters/__init__.py
  python/xorbits/xgboost/mars_adapters/core.py
  python/xorbits/xgboost/mars_adapters/tests/__init__.py
  python/xorbits/xgboost/mars_adapters/tests/test_classifier.py
  python/xorbits/xgboost/mars_adapters/tests/test_predict.py
  python/xorbits/xgboost/mars_adapters/tests/test_regressor.py
  python/xorbits/xgboost/mars_adapters/tests/test_train.py
  python/xorbits/xgboost/test/__init__.py
  python/xorbits/xgboost/test/test_core.py
Labels: feature

#506 BUG: fix `sort_index` bug of multi-level indexed Dataframe with multi-chunk
  python/xorbits/_mars/dataframe/sort/psrs.py
  python/xorbits/_mars/dataframe/sort/sort_index.py
  python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
Labels: bug

#532 BUG: fix dataframe sample
  python/xorbits/_mars/dataframe/indexing/sample.py
  python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
Labels: bug

#537 Bug: Fix numpy CI
  python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
  python/xorbits/_mars/optimization/logical/tileable/tests/test_head.py
  python/xorbits/_mars/tensor/reduction/core.py
  python/xorbits/_mars/tensor/statistics/tests/test_statistics.py
  python/xorbits/core/adapter.py
  python/xorbits/numpy/__init__.py
  python/xorbits/numpy/fft/__init__.py
  python/xorbits/numpy/linalg/__init__.py
  python/xorbits/numpy/mars_adapters/tests/test_numpy_examples.py
  python/xorbits/numpy/numpy_adapters/core.py
  python/xorbits/numpy/random/__init__.py
Labels: bug

#525 DOC: Init Xgboost Doc
  README.md
  doc/source/reference/index.rst
  doc/source/reference/xgboost/core.rst
  doc/source/reference/xgboost/index.rst
  doc/source/reference/xgboost/learning_api.rst
  doc/source/reference/xgboost/sklearn.rst
  python/xorbits/__init__.py
  python/xorbits/xgboost/__init__.py
  python/xorbits/xgboost/mars_adapters/core.py
Labels: documentation

#520 ENH: Fix the incompatibility with the latest version of SQLAlchemy.
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/datasource/read_sql.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/datastore/to_csv.py
  python/xorbits/_mars/utils.py
Labels: enhancement

#518 DOC: Updated doc for python support version
  doc/source/getting_started/installation.rst
Labels: documentation

#539 DOC: Install xgboost for doc building
  doc/source/index.rst
  python/setup.cfg
Labels: documentation

#541 BUG: fix lightgbm
  python/xorbits/lightgbm/__init__.py
Labels: bug

#540 DOC: Add lightgbm doc
  README.md
  doc/source/index.rst
  doc/source/reference/index.rst
  doc/source/reference/lightgbm/index.rst
  doc/source/reference/lightgbm/learning.rst
  doc/source/reference/lightgbm/sklearn.rst
  python/setup.cfg
Labels: documentation

#543 BUG: Suppress scipy warnings
  python/xorbits/_mars/learn/utils/multiclass.py
  python/xorbits/core/adapter.py
  python/xorbits/lightgbm/mars_adapters/core.py
  python/xorbits/xgboost/mars_adapters/core.py
Labels: bug

#497 FEAT: External Storage JuiceFS on K8S
  .github/workflows/python.yaml
  python/xorbits/_mars/storage/filesystem.py
  python/xorbits/_mars/storage/tests/test_libs.py
  python/xorbits/deploy/kubernetes/client.py
  python/xorbits/deploy/kubernetes/config.py
  python/xorbits/deploy/kubernetes/external_storage/__init__.py
  python/xorbits/deploy/kubernetes/external_storage/external_storage.py
  python/xorbits/deploy/kubernetes/external_storage/juicefs/__init__.py
  python/xorbits/deploy/kubernetes/external_storage/juicefs/config.py
  python/xorbits/deploy/kubernetes/external_storage/juicefs/tests/__init__.py
  python/xorbits/deploy/kubernetes/external_storage/juicefs/tests/example-redis-config.yaml
  python/xorbits/deploy/kubernetes/external_storage/juicefs/tests/test_juicefs.py
  python/xorbits/deploy/kubernetes/external_storage/juicefs/tests/values.yaml
  python/xorbits/deploy/kubernetes/supervisor.py
  python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
  python/xorbits/deploy/kubernetes/worker.py
Labels: feature

#538 DOC: Documentation for JuiceFS on Kubernetes
  doc/source/user_guide/deployment_cloud.rst
  doc/source/user_guide/deployment_kubernetes.rst
Labels: documentation

#545 BUG: Fix password lost when calling `pd.read_sql`
  python/xorbits/_mars/dataframe/datasource/read_sql.py
Labels: bug

#547 BUG: Fix error for unsupported input type of `read_sql`
  python/xorbits/_mars/dataframe/utils.py
Labels: bug

#550 BUG: fix sparse divide CI
  python/xorbits/_mars/lib/sparse/tests/test_sparse.py
Labels: bug

#554 BUG: fix joblib CI
  python/xorbits/_mars/learn/contrib/joblib/tests/test_backend.py
Labels: bug

#551 DOC: Add Chinese doc for external storage JuiceFS on K8S
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_kubernetes.po
  doc/source/user_guide/deployment_kubernetes.rst
Labels: documentation
