Repository xorbitsai/xorbits, pull requests merged in 2023-10, with the labels that each got.

#726 ENH: groupby.nunique supports by series
  python/xorbits/_mars/dataframe/groupby/aggregation.py
  python/xorbits/_mars/dataframe/groupby/nunique.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_nunique_execution.py
Labels: enhancement

#732 BUG: read parquet from s3 error: No Such Bucket
  .pre-commit-config.yaml
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/learn/linear_model/_base.py
  python/xorbits/_mars/learn/linear_model/tests/test_base.py
  python/xorbits/_mars/learn/metrics/pairwise/pairwise.py
  python/xorbits/_mars/tensor/base/tile.py
  python/xorbits/_mars/tensor/utils.py
Labels: bug

#736 BUG: Fix read_csv with index_col
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: bug

#704 FEAT: Support `read_csv` via `http`
  python/xorbits/_mars/dataframe/datasource/core.py
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: feature

#740 BUG: `merge` performance issue caused by `DataFrameAutoMergeMixin`
  python/xorbits/_mars/dataframe/base/cartesian_chunk.py
  python/xorbits/_mars/dataframe/base/core.py
  python/xorbits/_mars/dataframe/merge/merge.py
Labels: bug

#716 FEAT: Add `xorbits.sklearn` module
  python/xorbits/__init__.py
  python/xorbits/sklearn/__init__.py
  python/xorbits/sklearn/cluster/__init__.py
  python/xorbits/sklearn/cluster/mars_adapters/__init__.py
  python/xorbits/sklearn/cluster/mars_adapters/core.py
  python/xorbits/sklearn/cluster/tests/__init__.py
  python/xorbits/sklearn/cluster/tests/test_core.py
  python/xorbits/sklearn/datasets/__init__.py
  python/xorbits/sklearn/datasets/mars_adapters/__init__.py
  python/xorbits/sklearn/datasets/mars_adapters/core.py
  python/xorbits/sklearn/datasets/tests/__init__.py
  python/xorbits/sklearn/datasets/tests/test_core.py
  python/xorbits/sklearn/decomposition/__init__.py
  python/xorbits/sklearn/decomposition/mars_adapters/__init__.py
  python/xorbits/sklearn/decomposition/mars_adapters/core.py
  python/xorbits/sklearn/decomposition/tests/__init__.py
  python/xorbits/sklearn/decomposition/tests/test_core.py
  python/xorbits/sklearn/ensemble/__init__.py
  python/xorbits/sklearn/ensemble/mars_adapters/__init__.py
  python/xorbits/sklearn/ensemble/mars_adapters/core.py
  python/xorbits/sklearn/ensemble/tests/__init__.py
  python/xorbits/sklearn/ensemble/tests/test_core.py
  python/xorbits/sklearn/linear_model/__init__.py
  python/xorbits/sklearn/linear_model/mars_adapters/__init__.py
  python/xorbits/sklearn/linear_model/mars_adapters/core.py
  python/xorbits/sklearn/linear_model/tests/__init__.py
  python/xorbits/sklearn/linear_model/tests/test_core.py
  python/xorbits/sklearn/metrics/__init__.py
  python/xorbits/sklearn/metrics/mars_adapters/__init__.py
  python/xorbits/sklearn/metrics/mars_adapters/core.py
  python/xorbits/sklearn/metrics/tests/__init__.py
  python/xorbits/sklearn/metrics/tests/test_core.py
  python/xorbits/sklearn/model_selection/__init__.py
  python/xorbits/sklearn/model_selection/mars_adapters/__init__.py
  python/xorbits/sklearn/model_selection/mars_adapters/core.py
  python/xorbits/sklearn/model_selection/tests/__init__.py
  python/xorbits/sklearn/model_selection/tests/test_core.py
  python/xorbits/sklearn/neighbors/__init__.py
  python/xorbits/sklearn/neighbors/mars_adapters/__init__.py
  python/xorbits/sklearn/neighbors/mars_adapters/core.py
  python/xorbits/sklearn/neighbors/tests/__init__.py
  python/xorbits/sklearn/neighbors/tests/test_core.py
  python/xorbits/sklearn/preprocessing/__init__.py
  python/xorbits/sklearn/preprocessing/mars_adapters/__init__.py
  python/xorbits/sklearn/preprocessing/mars_adapters/core.py
  python/xorbits/sklearn/preprocessing/tests/__init__.py
  python/xorbits/sklearn/preprocessing/tests/test_core.py
  python/xorbits/sklearn/semi_supervised/__init__.py
  python/xorbits/sklearn/semi_supervised/mars_adapters/__init__.py
  python/xorbits/sklearn/semi_supervised/mars_adapters/core.py
  python/xorbits/sklearn/semi_supervised/tests/__init__.py
  python/xorbits/sklearn/semi_supervised/tests/test_core.py
  python/xorbits/sklearn/utils.py
Labels: feature

#748 TST: Fix xorbits.sklearn windows CI
  python/xorbits/_mars/tensor/statistics/bincount.py
  python/xorbits/_mars/utils.py
Labels: testing

#743 BUG: column pruning causes missing columns on `DataFrameIndex` op
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/column_pruning_rule.py
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_column_pruning.py
Labels: bug

#719 FEAT: Slurm Deployment For Xorbits
  .github/workflows/python.yaml
  .gitignore
  CI/slurm/Dockerfile
  CI/slurm/docker-compose.yml
  CI/slurm/register_cluster.sh
  CI/slurm/slurm.conf
  CI/slurm/slurm.sh
  CI/slurm/start-slurm.sh
  doc/source/user_guide/deployment_slurm.rst
  python/setup.cfg
  python/xorbits/deploy/slurm/__init__.py
  python/xorbits/deploy/slurm/slurm.py
  python/xorbits/deploy/slurm/tests/__init__.py
  python/xorbits/deploy/slurm/tests/test_slurm.py
Labels: feature
