Repository xorbitsai/xorbits, pull requests merged in 2023-09, with the labels that each got.

#676 DOC: Readme for tpch benchmark script
  benchmarks/tpch/README.md
  benchmarks/tpch/generate_data_pq.py
  benchmarks/tpch/loader.py
  benchmarks/tpch/run_queries.py
Labels: documentation

#675 ENH: Use memoryview to open reader in MMAP storage backend
  python/xorbits/_mars/storage/core.py
  python/xorbits/_mars/storage/mmap.py
Labels: enhancement

#662 FEAT: support loading zip file for read_parquet
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: feature

#679 ENH: Compatible with Pandas 2.1.0
  .github/workflows/python.yaml
  doc/source/libraries/xorbits_data/pandas.rst
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/dataframe/groupby/aggregation.py
  python/xorbits/_mars/dataframe/groupby/fill.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/hash_utils.py
  python/xorbits/_mars/dataframe/reduction/aggregation.py
  python/xorbits/_mars/dataframe/tests/test_utils.py
  python/xorbits/_mars/dataframe/utils.py
  python/xorbits/pandas/mars_adapters/tests/test_pandas_examples.py
  python/xorbits/pandas/pandas_adapters/core.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Labels: enhancement

#580 ENH: Improve use_arrow_dtype for pandas 2.0+
  python/xorbits/_mars/dataframe/__init__.py
  python/xorbits/_mars/dataframe/arrays.py
  python/xorbits/_mars/dataframe/base/apply.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/read_sql.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/groupby/aggregation.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/reduction/nunique.py
  python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
  python/xorbits/_mars/dataframe/tests/test_arrays.py
  python/xorbits/_mars/dataframe/utils.py
  python/xorbits/_mars/tests/test_utils.py
  python/xorbits/_mars/utils.py
Labels: enhancement, gpu

#681 BUG: ipython data missing columns due to column pruning
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/indexing/align.py
  python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
  python/xorbits/_mars/deploy/oscar/session.py
  python/xorbits/_mars/optimization/logical/chunk/__init__.py
  python/xorbits/_mars/optimization/logical/chunk/column_pruning.py
  python/xorbits/_mars/optimization/logical/chunk/tests/test_column_pruning.py
  python/xorbits/_mars/optimization/logical/common/column_pruning.py
Labels: bug

#685 ENH: Default enable arrow dtype for read_parquet if pandas>=2.1
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_hdfs.py
  python/xorbits/_mars/dataframe/datastore/tests/test_datastore_execution.py
  python/xorbits/_mars/dataframe/datastore/tests/test_datastore_hdfs.py
  python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
  python/xorbits/_mars/learn/contrib/lightgbm/tests/test_classifier.py
  python/xorbits/_mars/learn/contrib/xgboost/tests/test_classifier.py
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_column_pruning.py
  python/xorbits/_mars/optimization/logical/tileable/tests/test_head.py
  python/xorbits/_mars/tests/core.py
  python/xorbits/lightgbm/tests/test_classifier.py
Labels: enhancement

#677 ENH: Add a status monitor to trace the running stage of subtask
  python/xorbits/_mars/services/scheduling/api/oscar.py
  python/xorbits/_mars/services/scheduling/worker/__init__.py
  python/xorbits/_mars/services/scheduling/worker/execution.py
  python/xorbits/_mars/services/scheduling/worker/quota.py
  python/xorbits/_mars/services/scheduling/worker/service.py
  python/xorbits/_mars/services/scheduling/worker/tests/test_execution.py
  python/xorbits/_mars/services/scheduling/worker/tests/test_quota.py
  python/xorbits/_mars/services/subtask/__init__.py
  python/xorbits/_mars/services/subtask/core.py
Labels: enhancement

#531 ENH: impl array protocol for series and index
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/_mars/dataframe/tests/test_core.py
Labels: enhancement

#698 BLD: ADLFS import error and docker build failed
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#697 BUG: Tensor map chunk error when func is `tolist`
  python/xorbits/_mars/tensor/core.py
  python/xorbits/_mars/tensor/tests/test_core_execution.py
  python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py
Labels: bug

#699 ENH: added auto merge for cartesian_chunk
  python/xorbits/_mars/dataframe/base/cartesian_chunk.py
  python/xorbits/_mars/dataframe/base/core.py
  python/xorbits/_mars/dataframe/merge/merge.py
Labels: enhancement

#707 BUG: `df.agg` with kwargs
  python/xorbits/_mars/dataframe/reduction/aggregation.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
Labels: bug

#708 BUG: Column pruning failed when `groupby` by multi series
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/input_column_selector.py
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_input_column_selector.py
Labels: bug

#695 ENH: Add a check whether scheduling is stuck
  python/xorbits/_mars/deploy/oscar/base_config.yml
  python/xorbits/_mars/services/scheduling/worker/execution.py
  python/xorbits/_mars/services/scheduling/worker/service.py
  python/xorbits/_mars/services/scheduling/worker/tests/test_execution.py
Labels: enhancement

#715 ENH: Compatible with scikit-learn 1.3.1
  python/xorbits/_mars/learn/neighbors/base.py
Labels: enhancement

#709 BUG: fix df deep copy
  python/xorbits/_mars/core/base.py
  python/xorbits/_mars/core/entity/tileables.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/_mars/deploy/oscar/session.py
  python/xorbits/core/adapter.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Labels: bug

#684 FEAT: Add `Dataframe.Groupby.nth`
  python/xorbits/_mars/dataframe/groupby/__init__.py
  python/xorbits/_mars/dataframe/groupby/nth.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
Labels: feature

#722 BUG: df.groupby.agg error when func is nunique with tuple kwargs
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/groupby/aggregation.py
  python/xorbits/_mars/dataframe/groupby/nunique.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_nunique_execution.py
Labels: bug
