Repository xorbitsai/xorbits, pull requests merged in 2023-04, with the labels that each got.

#292 BUG: runtime error caused by read_csv and read_parquet with relative path
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/datasource/utils.py
Labels: bug

#322 TST: Fix pandas version
  .github/workflows/python.yaml
  doc/requirements-doc.txt
  python/setup.cfg
Labels: testing

#320 TST: refine ut and add 'convert_to_abspath' ut
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_utils.py
Labels: testing

#332 DOC: added SLURM doc links
  README.md
  doc/source/getting_started/deployment.rst
  doc/source/getting_started/index.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/deployment.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
Labels: documentation

#325 BUG: Fix local init for multiple GPU devices
  python/xorbits/_mars/deploy/oscar/local.py
  python/xorbits/_mars/deploy/oscar/tests/test_local.py
Labels: bug

#336 BUG: Int Auto Conversion
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_execution.py
Labels: bug

#311 ENH: Support Scale Up on K8S
  .gitignore
  python/xorbits/_mars/services/cluster/api/oscar.py
  python/xorbits/_mars/services/cluster/api/web.py
  python/xorbits/_mars/services/cluster/backends/base.py
  python/xorbits/_mars/services/cluster/supervisor/node_allocator.py
  python/xorbits/_mars/services/cluster/tests/test_api.py
  python/xorbits/deploy/kubernetes/config.py
  python/xorbits/deploy/kubernetes/core.py
  python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
Labels: enhancement

#340 BUG: unexpected error from `DataFrame.__mars_tensor__`
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/_mars/dataframe/tests/test_core.py
Labels: bug

#342 ENH: GPU benchmark script
  benchmarks/tpch/run_queries.py
Labels: enhancement

#326 BUG: No permission to chmod when multi users on the same machine
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/logging.po
  doc/source/user_guide/logging.rst
  python/xorbits/_mars/constants.py
  python/xorbits/_mars/deploy/oscar/pool.py
  python/xorbits/_mars/deploy/oscar/tests/test_pool.py
  python/xorbits/_mars/services/task/task_info_collector.py
Labels: bug

#247 BUG: equality assertion on lazy loaded cupy
  python/xorbits/_mars/learn/cluster/_k_means_common.py
  python/xorbits/_mars/learn/cluster/_k_means_elkan_iter.py
  python/xorbits/_mars/learn/cluster/_k_means_lloyd_iter.py
  python/xorbits/_mars/learn/metrics/pairwise/haversine.py
  python/xorbits/_mars/learn/metrics/pairwise/pairwise_distances_topk.py
  python/xorbits/_mars/learn/preprocessing/normalize.py
  python/xorbits/_mars/learn/utils/shuffle.py
  python/xorbits/_mars/lib/sparse/__init__.py
  python/xorbits/_mars/lib/sparse/array.py
  python/xorbits/_mars/lib/sparse/core.py
  python/xorbits/_mars/tensor/array_utils.py
  python/xorbits/_mars/tensor/base/astype.py
  python/xorbits/_mars/tensor/base/psrs.py
  python/xorbits/_mars/tensor/base/unique.py
  python/xorbits/_mars/tensor/datasource/array.py
  python/xorbits/_mars/tensor/einsum/core.py
  python/xorbits/_mars/tensor/linalg/cholesky.py
  python/xorbits/_mars/tensor/linalg/lu.py
  python/xorbits/_mars/tensor/linalg/solve_triangular.py
  python/xorbits/_mars/tensor/random/core.py
  python/xorbits/_mars/tensor/random/multivariate_normal.py
  python/xorbits/_mars/tensor/spatial/distance/cdist.py
  python/xorbits/_mars/tensor/spatial/distance/pdist.py
  python/xorbits/_mars/tensor/spatial/distance/squareform.py
  python/xorbits/_mars/tensor/special/core.py
  python/xorbits/_mars/tests/test_utils.py
  python/xorbits/_mars/utils.py
Labels: bug

#343 BUG: Xorbits.numpy raises TypeError
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_execution.py
Labels: bug

#355 BUG: fetch vram data from cluster
  python/xorbits/_mars/services/storage/api/oscar.py
  python/xorbits/_mars/services/storage/api/web.py
  python/xorbits/_mars/services/storage/handler.py
  python/xorbits/_mars/services/storage/tests/test_service.py
Labels: bug

#323 ENH: implement synchronous SGD for Logistic Regression
  python/xorbits/_mars/learn/glm/_optimizers.py
  python/xorbits/_mars/learn/glm/tests/test_logistic.py
Labels: enhancement

#346 ENH: Support DF and Series agg on GPU
  python/xorbits/_mars/core/operand/core.py
  python/xorbits/_mars/dataframe/reduction/aggregation.py
  python/xorbits/_mars/dataframe/reduction/core.py
  python/xorbits/_mars/dataframe/reduction/nunique.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
  python/xorbits/_mars/tests/core.py
Labels: enhancement, gpu

#357 BUG: fetch vram data from local cluster
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
  python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
  python/xorbits/_mars/dataframe/tests/test_initializer.py
  python/xorbits/_mars/dataframe/tseries/tests/test_tseries_execution.py
  python/xorbits/_mars/deploy/oscar/session.py
  python/xorbits/_mars/deploy/oscar/tests/session.py
  python/xorbits/_mars/services/storage/api/web.py
  python/xorbits/_mars/services/task/execution/mars/fetcher.py
  python/xorbits/_mars/tensor/arithmetic/tests/test_arithmetic_execution.py
  python/xorbits/_mars/tensor/base/tests/test_base_execution.py
Labels: bug, gpu

#373 TST: fix GPU tests
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
Labels: testing, gpu

#374 CLN: remove mutable service
  python/xorbits/_mars/deploy/oscar/base_config.yml
  python/xorbits/_mars/deploy/oscar/session.py
  python/xorbits/_mars/services/mutable/__init__.py
  python/xorbits/_mars/services/mutable/api/__init__.py
  python/xorbits/_mars/services/mutable/api/core.py
  python/xorbits/_mars/services/mutable/api/oscar.py
  python/xorbits/_mars/services/mutable/api/web.py
  python/xorbits/_mars/services/mutable/core.py
  python/xorbits/_mars/services/mutable/supervisor/__init__.py
  python/xorbits/_mars/services/mutable/supervisor/core.py
  python/xorbits/_mars/services/mutable/supervisor/service.py
  python/xorbits/_mars/services/mutable/tests/__init__.py
  python/xorbits/_mars/services/mutable/tests/test_mutable.py
  python/xorbits/_mars/services/mutable/utils.py
  python/xorbits/_mars/services/mutable/worker/__init__.py
  python/xorbits/_mars/services/mutable/worker/core.py
  python/xorbits/_mars/services/scheduling/tests/test_service.py
  python/xorbits/_mars/services/scheduling/worker/tests/test_execution.py
  python/xorbits/_mars/services/session/tests/test_service.py
  python/xorbits/_mars/services/subtask/tests/test_service.py
  python/xorbits/_mars/services/subtask/worker/tests/test_subtask.py
  python/xorbits/_mars/services/task/supervisor/tests/test_task_manager.py
  python/xorbits/_mars/services/task/tests/test_service.py
Labels: enhancement

#328 ENH: Compatible with pandas 2.0
  .github/workflows/python.yaml
  doc/requirements-doc.txt
  python/setup.cfg
  python/xorbits/_mars/dataframe/base/bloom_filter.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/dataframe/base/value_counts.py
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/_mars/dataframe/datasource/from_tensor.py
  python/xorbits/_mars/dataframe/datasource/read_sql.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/datastore/to_csv.py
  python/xorbits/_mars/dataframe/datastore/to_parquet.py
  python/xorbits/_mars/dataframe/datastore/to_sql.py
  python/xorbits/_mars/dataframe/groupby/core.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_nunique_execution.py
  python/xorbits/_mars/dataframe/indexing/index_lib.py
  python/xorbits/_mars/dataframe/indexing/loc.py
  python/xorbits/_mars/dataframe/indexing/reindex.py
  python/xorbits/_mars/dataframe/indexing/set_axis.py
  python/xorbits/_mars/dataframe/indexing/where.py
  python/xorbits/_mars/dataframe/merge/merge.py
  python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
  python/xorbits/_mars/dataframe/missing/fillna.py
  python/xorbits/_mars/dataframe/reduction/nunique.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
  python/xorbits/_mars/dataframe/statistics/corr.py
  python/xorbits/_mars/dataframe/statistics/quantile.py
  python/xorbits/_mars/dataframe/statistics/tests/test_statistics.py
  python/xorbits/_mars/dataframe/statistics/tests/test_statistics_execution.py
  python/xorbits/_mars/dataframe/tests/test_arrays.py
  python/xorbits/_mars/dataframe/tests/test_utils.py
  python/xorbits/_mars/dataframe/utils.py
  python/xorbits/_mars/dataframe/window/ewm/tests/test_ewm_execution.py
  python/xorbits/_mars/dataframe/window/expanding/aggregation.py
  python/xorbits/_mars/dataframe/window/expanding/core.py
  python/xorbits/_mars/dataframe/window/expanding/tests/test_expanding.py
  python/xorbits/_mars/dataframe/window/expanding/tests/test_expanding_execution.py
  python/xorbits/_mars/dataframe/window/rolling/core.py
  python/xorbits/_mars/dataframe/window/rolling/tests/test_rolling_execution.py
  python/xorbits/_mars/learn/contrib/lightgbm/tests/test_classifier.py
  python/xorbits/_mars/learn/contrib/tsfresh/tests/test_tsfresh.py
  python/xorbits/_mars/learn/utils/shuffle.py
  python/xorbits/_mars/lib/groupby_wrapper.py
  python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_input_column_selector.py
  python/xorbits/_mars/tests/core.py
  python/xorbits/_mars/tests/test_session.py
  python/xorbits/_mars/utils.py
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
Labels: enhancement

#370 BUG: Fix ```pd.__dir__()```
  python/xorbits/pandas/__init__.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Labels: bug

#354 BUG: Fix df.groupby.size on GPU
  python/xorbits/_mars/dataframe/groupby/aggregation.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
Labels: bug, gpu

#381 BUG: fetching from GPU
  python/xorbits/_mars/dataframe/tests/test_utils.py
  python/xorbits/_mars/dataframe/utils.py
  python/xorbits/_mars/storage/cuda.py
  python/xorbits/_mars/storage/tests/test_libs.py
Labels: bug, gpu

#372 ENH: remove global vars in adapters
  python/xorbits/numpy/__init__.py
  python/xorbits/numpy/fft/__init__.py
  python/xorbits/numpy/linalg/__init__.py
  python/xorbits/numpy/numpy_adapters/core.py
  python/xorbits/numpy/random/__init__.py
  python/xorbits/pandas/__init__.py
  python/xorbits/pandas/pandas_adapters/core.py
Labels: enhancement

#386 TST: reuse existing tests for GPU testing
  .github/workflows/python.yaml
  python/xorbits/_mars/tests/core.py
  python/xorbits/conftest.py
Labels: testing, gpu

#388 BUG: destory session in xorbits.shutdown
  python/xorbits/deploy/__init__.py
Labels: bug

#379 ENH: Support arrow list type for `read_parquet`
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: enhancement

#367 BUG: DataFrameBinOp tile output dtype is wrong
  python/xorbits/_mars/dataframe/arithmetic/core.py
  python/xorbits/_mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
Labels: bug

#385 BUG: GPU `DataFrame` init from tensors or pandas dataframes
  python/xorbits/_mars/dataframe/datasource/dataframe.py
  python/xorbits/_mars/dataframe/datasource/from_tensor.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: bug, gpu

#383 BUG: Fix batch put and fetch data on GPU
  python/xorbits/_mars/services/scheduling/worker/execution.py
  python/xorbits/_mars/services/scheduling/worker/tests/test_execution.py
  python/xorbits/_mars/services/subtask/worker/processor.py
Labels: bug, gpu

#401 ENH: Move the logic for handling this `n_io_process` to xorbits
  CI/install-hadoop.sh
  python/xorbits/_mars/deploy/oscar/pool.py
Labels: enhancement

#392 FEAT: add alluxio storage lib
  .github/workflows/python.yaml
  python/xorbits/_mars/storage/filesystem.py
  python/xorbits/_mars/storage/tests/test_libs.py
Labels: feature

#398 BUG: Fix `estimate_size` of `DataFrameReadParquet`
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
Labels: bug

#368 BUG: Fix `DataFrame.set_axis` on GPU
  python/xorbits/_mars/dataframe/indexing/set_axis.py
  python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
Labels: bug, gpu

#282 BUG: add attribute '__array__' for mars dataframe
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/_mars/dataframe/tests/test_core.py
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_execution.py
  python/xorbits/numpy/mars_adapters/core.py
  python/xorbits/pandas/mars_adapters/core.py
Labels: bug

#414 BUG: series initializer on GPU
  python/xorbits/_mars/dataframe/datasource/from_tensor.py
  python/xorbits/_mars/dataframe/datasource/series.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/indexing/loc.py
  python/xorbits/_mars/dataframe/indexing/set_axis.py
  python/xorbits/_mars/services/storage/handler.py
Labels: bug, gpu

#409 BUG: GPU index initializer
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/_mars/dataframe/datasource/index.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/tests/core.py
Labels: bug, gpu

#411 BUG: Fix merge and join on GPU
  python/xorbits/_mars/dataframe/merge/merge.py
  python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
  python/xorbits/_mars/dataframe/utils.py
  python/xorbits/_mars/services/storage/handler.py
  python/xorbits/_mars/services/subtask/worker/processor.py
Labels: bug, gpu

#419 BUG: gpu dataframe iloc
  python/xorbits/_mars/dataframe/indexing/iloc.py
  python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
Labels: bug, gpu
