Repository xorbitsai/xorbits, pull requests merged in 2023-05, with the labels that each got.

#410 BUG: AttributeError when calling df.col
  python/xorbits/core/data.py
  python/xorbits/core/tests/test_adapter.py
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
Labels: bug

#422 BUG: Wrong dataframe id value
  python/xorbits/_mars/dataframe/core.py
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
Labels: bug

#427 BUG: Fix agg('size') execute map result, which should be a series rather than a df
  python/xorbits/_mars/dataframe/groupby/aggregation.py
Labels: bug

#431 CLN: Remove k8s deploy in _mars
  python/xorbits/_mars/deploy/kubernetes/__init__.py
  python/xorbits/_mars/deploy/kubernetes/client.py
  python/xorbits/_mars/deploy/kubernetes/config.py
  python/xorbits/_mars/deploy/kubernetes/config.yml
  python/xorbits/_mars/deploy/kubernetes/core.py
  python/xorbits/_mars/deploy/kubernetes/docker/Dockerfile
  python/xorbits/_mars/deploy/kubernetes/docker/Dockerfile.base
  python/xorbits/_mars/deploy/kubernetes/docker/entrypoint.sh
  python/xorbits/_mars/deploy/kubernetes/docker/retry.sh
  python/xorbits/_mars/deploy/kubernetes/supervisor.py
  python/xorbits/_mars/deploy/kubernetes/tests/Dockerfile.test
  python/xorbits/_mars/deploy/kubernetes/tests/__init__.py
  python/xorbits/_mars/deploy/kubernetes/tests/build_ext.sh
  python/xorbits/_mars/deploy/kubernetes/tests/docker-logging.conf
  python/xorbits/_mars/deploy/kubernetes/tests/entrypoint.sh
  python/xorbits/_mars/deploy/kubernetes/tests/graceful_stop.sh
  python/xorbits/_mars/deploy/kubernetes/tests/test_config.py
  python/xorbits/_mars/deploy/kubernetes/tests/test_kubernetes.py
  python/xorbits/_mars/deploy/kubernetes/worker.py
Labels: enhancement

#421 FEAT: implement ```sklearn.model_selection.ParameterGrid```
  python/xorbits/_mars/learn/model_selection/__init__.py
  python/xorbits/_mars/learn/model_selection/_search.py
  python/xorbits/_mars/learn/model_selection/tests/test_search.py
Labels: feature

#433 BUG: groupby same agg funcs leads to wrong results
  python/xorbits/_mars/dataframe/groupby/aggregation.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/reduction/aggregation.py
  python/xorbits/_mars/dataframe/reduction/core.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
Labels: bug

#445 FEAT: Support Applymap Operand
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/base/__init__.py
  python/xorbits/_mars/dataframe/base/applymap.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/opcodes.py
Labels: feature

#449 BLD: Restrict numpy version in docker for python 3.8 and 3.9
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#451 DOC: fix the docs issue link
  doc/source/development/contributing_documentation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po
Labels: documentation

#455 DOC: correct dev doc
  doc/source/development/contributing_documentation.rst
Labels: documentation

#453 FEAT: Add JuiceFs as an alternative storage
  .github/workflows/python.yaml
  python/xorbits/_mars/storage/filesystem.py
  python/xorbits/_mars/storage/tests/test_libs.py
Labels: feature

#452 BLD: Change conda numpy and scipy channel in docker build for python 3.8
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#436 BUG: Value Error when using dataframes' results to initialize a new dataframe
  python/xorbits/_mars/dataframe/initializer.py
  python/xorbits/_mars/dataframe/tests/test_initializer.py
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
Labels: bug

#457 DOC: git usage zh_cn
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing.po
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po
Labels: documentation

#459 DOC: update pot files
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/array-creation.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/array-manipulation.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/bitwise.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/indexing.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/io.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/linalg.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/logic.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/math.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/set.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/sort.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/statistics.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/frame.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/general_functions.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/groupby.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/indexing.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/io.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/series.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/window.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/xorbits/index.po
Labels: documentation

#463 DOC: Check doc building in CI
  .github/workflows/python.yaml
Labels: documentation

#458 DOC: translate documentation development
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po
Labels: documentation

#448 FEAT: groupby rolling
  python/xorbits/_mars/dataframe/groupby/__init__.py
  python/xorbits/_mars/dataframe/groupby/rolling.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/opcodes.py
Labels: feature

#468 DOC: remove `fuzzy` statements
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po
Labels: documentation

#434 ENH: Support numpy.ndarray fallback to numpy
  python/xorbits/core/adapter.py
  python/xorbits/numpy/__init__.py
  python/xorbits/numpy/numpy_adapters/__init__.py
  python/xorbits/numpy/numpy_adapters/core.py
  python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py
  python/xorbits/pandas/pandas_adapters/core.py
Labels: enhancement

#450 FEAT: rolling cov
  python/xorbits/_mars/dataframe/window/rolling/aggregation.py
  python/xorbits/_mars/dataframe/window/rolling/core.py
  python/xorbits/_mars/dataframe/window/rolling/tests/test_rolling_execution.py
Labels: feature

#470 DOC: correct & translate creating dev env
  doc/source/development/contributing_environment.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
  python/conda-spec.txt
Labels: documentation

#440 FEAT: implement jax-based runtime graph fusion optimizer
  .github/workflows/python.yaml
  LICENSE
  python/setup.cfg
  python/xorbits/_mars/optimization/physical/__init__.py
  python/xorbits/_mars/optimization/physical/core.py
  python/xorbits/_mars/optimization/physical/jax.py
  python/xorbits/_mars/optimization/physical/numexpr.py
  python/xorbits/_mars/optimization/physical/tests/test_graph_traversal.py
  python/xorbits/_mars/services/task/config.py
  python/xorbits/_mars/tensor/__init__.py
  python/xorbits/_mars/tensor/fuse/__init__.py
  python/xorbits/_mars/tensor/fuse/jax.py
  python/xorbits/_mars/tensor/fuse/tests/test_runtime_fusion.py
  python/xorbits/deploy/docker/Dockerfile.base
Labels: feature, gpu

#430 BUG: series.tolist()[0] get Attribute Error
  python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
  python/xorbits/pandas/pandas_adapters/core.py
Labels: bug

#469 DOC: translation for the contributing doc
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing.po
Labels: documentation

#473 DOC: Fix docker development doc
  doc/source/development/contributing_environment.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
Labels: documentation

#472 BLD: add doc deps to setup.cfg
  .github/workflows/python.yaml
  .readthedocs.yaml
  doc/requirements-doc.txt
  python/setup.cfg
Labels: build

#480 BUG: pd.pivot
  python/xorbits/_mars/dataframe/__init__.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Labels: bug

#476 DOC: remove the readthedocs related content from dev docs
  doc/source/_static/ci.png
  doc/source/development/contributing_documentation.rst
Labels: documentation

#481 BLD: fix doc build
  python/setup.cfg
Labels: build
