Repository xorbitsai/xorbits, pull requests merged in 2023-03, with the labels that each got.

#252 BLD: Fixes cython compilation failures in Python 3.11.
  .github/workflows/python.yaml
  CI/requirements-wheel.txt
  python/pyproject.toml
  python/setup.cfg
  python/setup.py
Labels: build

#244 ENH: Support ```xorbits.numpy.random``` fallback to numpy
  python/xorbits/core/utils/fallback.py
  python/xorbits/core/utils/tests/test_fallback.py
  python/xorbits/numpy/numpy_adapters/__init__.py
  python/xorbits/numpy/numpy_adapters/core.py
  python/xorbits/numpy/numpy_adapters/tests/__init__.py
  python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py
  python/xorbits/numpy/random/__init__.py
  python/xorbits/pandas/__init__.py
  python/xorbits/pandas/pandas_adapters/core.py
Labels: enhancement

#243 ENH: dump runtime stats to cloud storage systems
  python/xorbits/_mars/constants.py
  python/xorbits/_mars/deploy/oscar/base_config.yml
  python/xorbits/_mars/lib/filesystem/__init__.py
  python/xorbits/_mars/lib/filesystem/core.py
  python/xorbits/_mars/services/subtask/worker/processor.py
  python/xorbits/_mars/services/task/api/oscar.py
  python/xorbits/_mars/services/task/supervisor/processor.py
  python/xorbits/_mars/services/task/supervisor/tests/test_task_manager.py
  python/xorbits/_mars/services/task/task_info_collector.py
Labels: enhancement

#265 BUG: delete node_modules dir in docker
  python/xorbits/deploy/docker/Dockerfile
Labels: bug

#263 BLD: Fix requirements for building wheel
  CI/requirements-wheel.txt
Labels: build

#259 ENH: Session id is prefixed with namespace in the k8s environment
  python/xorbits/_mars/deploy/oscar/session.py
  python/xorbits/_mars/services/cluster/gather.py
  python/xorbits/_mars/services/session/api/oscar.py
  python/xorbits/_mars/services/session/api/web.py
  python/xorbits/_mars/services/session/supervisor/core.py
  python/xorbits/_mars/services/session/tests/test_service.py
  python/xorbits/_mars/tests/test_utils.py
  python/xorbits/_mars/utils.py
  python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
Labels: enhancement

#262 BUG: Fix ```np.einsum``` error when computing trace
  python/xorbits/_mars/tensor/einsum/core.py
  python/xorbits/_mars/tensor/einsum/tests/test_einsum_execution.py
Labels: bug

#272 BLD: Add python *cp311* wheel support & drop *cp37* wheel build
  .github/workflows/build-wheel.yaml
  .github/workflows/python.yaml
  python/pyproject.toml
  python/setup.cfg
Labels: build

#274 BLD: Drop Python 3.7 and support Python 3.11 for docker and CI
  .github/mergify.yml
  .github/workflows/docker-cd.yaml
  .github/workflows/python.yaml
  python/xorbits/_mars/learn/contrib/utils.py
  python/xorbits/_mars/lib/aio/_runners.py
  python/xorbits/_mars/oscar/tests/test_batch.py
  python/xorbits/_mars/tests/test_utils.py
  python/xorbits/_mars/utils.py
  python/xorbits/compat/_constants.py
  python/xorbits/deploy/docker/Dockerfile
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#242 ENH: Use `get_index_and_uuid` to get device uuid
  python/xorbits/_mars/lib/nvutils.py
Labels: enhancement

#257 ENH: logging improvements
  python/xorbits/_mars/constants.py
  python/xorbits/_mars/deploy/oscar/base_config.yml
  python/xorbits/_mars/deploy/oscar/cmdline.py
  python/xorbits/_mars/deploy/oscar/file-logging.conf
  python/xorbits/_mars/deploy/oscar/pool.py
  python/xorbits/_mars/deploy/oscar/supervisor.py
  python/xorbits/_mars/deploy/oscar/tests/test_cmdline.py
  python/xorbits/_mars/deploy/oscar/tests/test_pool.py
  python/xorbits/_mars/oscar/backends/mars/pool.py
  python/xorbits/_mars/services/cluster/file_logger.py
  python/xorbits/_mars/services/cluster/tests/test_api.py
  python/xorbits/_mars/services/cluster/tests/test_file_logger.py
  python/xorbits/_mars/services/task/supervisor/tests/test_task_manager.py
  python/xorbits/_mars/services/task/task_info_collector.py
  python/xorbits/_mars/utils.py
  python/xorbits/deploy/docker/Dockerfile
  python/xorbits/deploy/docker/entrypoint.sh
  python/xorbits/deploy/oscar/file-logging.conf
  python/xorbits/tests/test_utils.py
  python/xorbits/utils.py
Labels: enhancement

#283 BUG: fix error when inputting 1d array for ```np.tril```
  python/xorbits/_mars/tensor/datasource/tests/test_datasource.py
  python/xorbits/_mars/tensor/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/tensor/datasource/tri.py
Labels: bug

#287 BUG: default logging not applied in interactive mode
  python/xorbits/_mars/deploy/oscar/cmdline.py
  python/xorbits/_mars/deploy/oscar/pool.py
  python/xorbits/_mars/deploy/yarn/config.py
  python/xorbits/deploy/__init__.py
Labels: bug

#291 BUG: Stop uploading node info after interpreter shutdown
  python/xorbits/_mars/services/cluster/uploader.py
  python/xorbits/_mars/services/storage/core.py
Labels: bug

#293 ENH: remove tblib
  python/pyproject.toml
  python/setup.cfg
  python/xorbits/_mars/lib/tblib/__init__.py
  python/xorbits/_mars/lib/tblib/cpython.py
  python/xorbits/_mars/lib/tblib/decorators.py
  python/xorbits/_mars/lib/tblib/pickling_support.py
Labels: enhancement

#296 ENH: use a single tempdir
  python/xorbits/_mars/constants.py
  python/xorbits/_mars/deploy/oscar/pool.py
  python/xorbits/_mars/deploy/oscar/tests/test_pool.py
  python/xorbits/_mars/deploy/yarn/client.py
  python/xorbits/_mars/deploy/yarn/config.py
  python/xorbits/_mars/deploy/yarn/tests/test_yarn.py
  python/xorbits/_mars/services/cluster/file_logger.py
  python/xorbits/_mars/services/cluster/tests/test_api.py
  python/xorbits/_mars/services/cluster/tests/test_file_logger.py
  python/xorbits/_mars/services/task/supervisor/tests/test_task_manager.py
  python/xorbits/_mars/services/task/task_info_collector.py
Labels: enhancement

#299 ENH: init extension entry point when importing
  python/xorbits/_mars/__init__.py
  python/xorbits/_mars/deploy/oscar/local.py
  python/xorbits/_mars/deploy/oscar/session.py
  python/xorbits/_mars/utils.py
Labels: enhancement

#307 CLN: Remove `read_raydataset`
  python/xorbits/_mars/dataframe/__init__.py
  python/xorbits/_mars/dataframe/datasource/read_raydataset.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/utils.py
Labels: enhancement

#306 DOC: logging
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/logging.po
  doc/source/user_guide/index.rst
  doc/source/user_guide/logging.rst
  python/xorbits/_mars/constants.py
Labels: documentation

#284 ENH: support numpy fallback
  python/xorbits/numpy/__init__.py
  python/xorbits/numpy/fft/__init__.py
  python/xorbits/numpy/linalg/__init__.py
  python/xorbits/numpy/mars_adapters/tests/test_numpy_examples.py
  python/xorbits/numpy/numpy_adapters/core.py
  python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py
  python/xorbits/numpy/random/__init__.py
Labels: enhancement

#313 FEAT: impl rolling.corr
  python/xorbits/_mars/dataframe/window/rolling/aggregation.py
  python/xorbits/_mars/dataframe/window/rolling/core.py
  python/xorbits/_mars/dataframe/window/rolling/tests/test_rolling_execution.py
Labels: feature

#314 DOC: K8s drops support for 3.7 and adds support for 3.11
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_kubernetes.po
  doc/source/user_guide/deployment_kubernetes.rst
Labels: documentation
