Repository xorbitsai/xorbits, pull requests merged in 2023-07, with the labels that each got.

#535 FEAT: Support pandas option
  python/xorbits/_mars/config.py
  python/xorbits/pandas/__init__.py
  python/xorbits/pandas/_config/__init__.py
  python/xorbits/pandas/_config/config.py
  python/xorbits/pandas/_config/test/__init__.py
  python/xorbits/pandas/_config/test/test_config.py
Labels: feature

#559 TST: Fix version of sklearn
  .github/workflows/python.yaml
Labels: testing

#556 DOC: update why xorbits
  doc/source/_static/adaptive_plan.png
  doc/source/_static/graph_fusion.png
  doc/source/_static/pandas_multicore.png
  doc/source/_static/xorbits_cluster.png
  doc/source/_static/xorbits_multicore.png
  doc/source/getting_started/deployment.rst
  doc/source/getting_started/examples.rst
  doc/source/getting_started/index.rst
  doc/source/getting_started/why_xorbits/comparisons.rst
  doc/source/getting_started/why_xorbits/fast.rst
  doc/source/getting_started/why_xorbits/index.rst
  doc/source/getting_started/why_xorbits/pandas.rst
  doc/source/index.rst
  doc/source/libraries/index.rst
  doc/source/libraries/xorbits_data/index.rst
  doc/source/libraries/xorbits_data/numpy.rst
  doc/source/libraries/xorbits_data/pandas.rst
  doc/source/libraries/xorbits_inference/index.rst
  doc/source/libraries/xorbits_train/index.rst
  doc/source/libraries/xorbits_tune/index.rst
Labels: documentation

#557 DOC: update readme
  README.md
Labels: documentation

#568 CLN: Fix github urls
  .github/workflows/asv.yaml
  .github/workflows/build-wheel.yaml
  .github/workflows/docker-cd.yaml
  README.md
  asv/asv.conf.json
  doc/source/conf.py
  doc/source/development/contributing.rst
  doc/source/development/contributing_documentation.rst
  doc/source/development/contributing_environment.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing.po
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/user_guide/deployment_kubernetes.rst
  python/setup.cfg
  python/xorbits/web/ui/package.json
  python/xorbits/web/ui/src/MainFrame.js
Labels: enhancement

#565 BUG: Fix build error on macos
  python/pyproject.toml
Labels: bug

#530 FEAT: Support nlargest and nsmallest op
  python/xorbits/_mars/dataframe/base/__init__.py
  python/xorbits/_mars/dataframe/base/nlargest.py
  python/xorbits/_mars/dataframe/base/nsmallest.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/opcodes.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Labels: feature

#575 BUG: Match more error message
  python/xorbits/_mars/services/cluster/uploader.py
  python/xorbits/_mars/services/storage/core.py
Labels: bug

#561 DOC: make the slurm docs more concise
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_slurm.po
  doc/source/user_guide/deployment_slurm.rst
Labels: documentation

#573 FEAT: Support read parquet from http urls
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: feature

#585 BLD: Fix scipy version in pyproject.toml
  python/pyproject.toml
Labels: build

#588 BUG: Fix StringAccessor __getitem__ error
  python/xorbits/core/adapter.py
  python/xorbits/core/tests/test_execution.py
Labels: bug

#589 BUG: Fix RuntimeError: cannot schedule new futures after shutdown
  python/pyproject.toml
  python/setup.cfg
  python/xorbits/_mars/services/cluster/uploader.py
Labels: bug

#582 ENH: Support xoscar copy_to
  .github/workflows/asv.yaml
  .github/workflows/python.yaml
  python/xorbits/_mars/deploy/oscar/base_config.yml
  python/xorbits/_mars/deploy/oscar/local.py
  python/xorbits/_mars/deploy/oscar/pool.py
  python/xorbits/_mars/deploy/oscar/tests/test_local.py
  python/xorbits/_mars/services/storage/core.py
  python/xorbits/_mars/services/storage/handler.py
  python/xorbits/_mars/services/storage/tests/test_transfer.py
  python/xorbits/_mars/services/storage/tests/test_transfer_gpu.py
  python/xorbits/_mars/services/storage/transfer.py
  python/xorbits/_mars/storage/core.py
  python/xorbits/_mars/storage/cuda.py
  python/xorbits/_mars/storage/shared_memory.py
  python/xorbits/_mars/storage/tests/test_libs.py
  python/xorbits/deploy/docker/Dockerfile.base
Labels: enhancement

#590 BUG: Fix Read Parquet
  python/xorbits/_mars/lib/filesystem/_glob.py
  python/xorbits/_mars/lib/filesystem/fsspec_adapter.py
Labels: bug

#599 BUG: Fix LGBM CI
  .github/workflows/python.yaml
Labels: bug

#598 BUG: Fetch to local when print object data
  python/xorbits/_mars/core/entity/objects.py
  python/xorbits/_mars/remote/tests/test_remote_function.py
  python/xorbits/_mars/resource.py
  python/xorbits/_mars/services/cluster/uploader.py
  python/xorbits/_mars/services/storage/core.py
  python/xorbits/_mars/utils.py
  python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
  python/xorbits/remote/mars_adapters/tests/test_mars_adapters.py
Labels: bug

#601 BUG: Fix compatibility with the newest lightgbm
  .github/workflows/python.yaml
  python/xorbits/_mars/learn/contrib/lightgbm/_train.py
  python/xorbits/_mars/learn/contrib/lightgbm/tests/test_classifier.py
  python/xorbits/_mars/learn/contrib/lightgbm/tests/test_ranker.py
  python/xorbits/_mars/learn/contrib/lightgbm/tests/test_regressor.py
  python/xorbits/lightgbm/tests/test_classifier.py
  python/xorbits/lightgbm/tests/test_ranker.py
  python/xorbits/lightgbm/tests/test_regressor.py
Labels: bug

#576 FEAT: support text dedup
  python/xorbits/_mars/_utils.pyx
  python/xorbits/_mars/dataframe/base/__init__.py
  python/xorbits/_mars/dataframe/base/dedup.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/opcodes.py
  python/xorbits/_mars/utils.py
Labels: feature

#611 FEAT: add xorbits experimental
  doc/source/reference/experimental/dedup.rst
  doc/source/reference/experimental/index.rst
  doc/source/reference/index.rst
  python/xorbits/__init__.py
  python/xorbits/_mars/dataframe/base/__init__.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/experimental/__init__.py
  python/xorbits/experimental/dedup.py
  python/xorbits/experimental/tests/__init__.py
  python/xorbits/experimental/tests/test_text_dedup.py
Labels: feature

#609 ENH: Optimize graph fusion
  python/xorbits/_mars/services/task/analyzer/analyzer.py
  python/xorbits/_mars/services/task/analyzer/fusion.py
  python/xorbits/_mars/services/task/analyzer/tests/test_fusion.py
Labels: enhancement

#612 BUG: fix s3 glob
  python/xorbits/_mars/lib/filesystem/_glob.py
Labels: bug

#600 FEAT: Basic datasets feature
  .github/workflows/python.yaml
  python/setup.cfg
  python/xorbits/__init__.py
  python/xorbits/_mars/core/entity/output_types.py
  python/xorbits/_mars/utils.py
  python/xorbits/core/data.py
  python/xorbits/datasets/__init__.py
  python/xorbits/datasets/adapter.py
  python/xorbits/datasets/backends/__init__.py
  python/xorbits/datasets/backends/huggingface/__init__.py
  python/xorbits/datasets/backends/huggingface/core.py
  python/xorbits/datasets/backends/huggingface/loader.py
  python/xorbits/datasets/backends/huggingface/map.py
  python/xorbits/datasets/backends/huggingface/rechunk.py
  python/xorbits/datasets/backends/huggingface/tests/__init__.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
  python/xorbits/datasets/backends/huggingface/to_dataframe.py
  python/xorbits/datasets/dataset.py
  python/xorbits/datasets/operand.py
  python/xorbits/utils.py
Labels: feature

#614 BUG: Fix `pd.read_csv` with encoding parameter
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: bug

#621 FEAT: Raise clearer errors when encountering OOM
  python/setup.cfg
  python/xorbits/_mars/services/scheduling/worker/execution.py
  python/xorbits/core/tests/test_execution.py
Labels: feature

#620 DOC: Add best practice for loading data
  doc/source/getting_started/examples.rst
  doc/source/user_guide/best_practices.rst
  doc/source/user_guide/index.rst
  doc/source/user_guide/loading_data.rst
Labels: documentation

#625 BUG: fix from_tensor
  python/xorbits/_mars/dataframe/datasource/from_tensor.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Labels: bug

#619 Doc: Datasets doc
  doc/source/libraries/xorbits_data/datasets.rst
  doc/source/libraries/xorbits_data/index.rst
  doc/source/reference/datasets/dataset.rst
  doc/source/reference/datasets/index.rst
  doc/source/reference/datasets/io.rst
  doc/source/reference/index.rst
  python/setup.cfg
  python/xorbits/datasets/__init__.py
  python/xorbits/datasets/adapter.py
  python/xorbits/datasets/backends/huggingface/core.py
  python/xorbits/datasets/dataset.py
Labels: documentation

#617 ENH: add dedup method
  python/xorbits/experimental/dedup.py
  python/xorbits/experimental/tests/test_text_dedup.py
  python/xorbits/experimental/utils.py
Labels: enhancement

#627 BUG: fix drop_duplicates no dtypes
  python/xorbits/_mars/dataframe/base/_duplicate.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
Labels: bug

#628 Feat: Basic datasets getitem
  doc/source/libraries/xorbits_data/datasets.rst
  python/xorbits/_mars/services/meta/metas.py
  python/xorbits/_mars/services/task/supervisor/tests/task_preprocessor.py
  python/xorbits/_mars/utils.py
  python/xorbits/datasets/backends/huggingface/core.py
  python/xorbits/datasets/backends/huggingface/getitem.py
  python/xorbits/datasets/backends/huggingface/loader.py
  python/xorbits/datasets/backends/huggingface/map.py
  python/xorbits/datasets/backends/huggingface/rechunk.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
  python/xorbits/datasets/backends/huggingface/to_dataframe.py
  python/xorbits/datasets/dataset.py
Labels: feature
