Repository xorbitsai/xorbits, pull requests merged in 2024-12, with the labels that each got.

#832 BUG: Fix no build_categorical_column error of GPU read_parquet
  .github/workflows/python.yaml
  doc/source/getting_started/installation.rst
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
Labels: bug, gpu

#833 BLD: build wheel CI upgrade macos-12 to macos-13
  .github/workflows/build-wheel.yaml
Labels: build

#835 ENH: update web ui deps & remove deprecated numpy.compat
  CI/test_basic_execution.py
  python/xorbits/_mars/tensor/einsum/einsumfunc.py
  python/xorbits/web/ui/package-lock.json
  python/xorbits/web/ui/package.json
  python/xorbits/web/ui/src/MainFrame.js
Labels: enhancement

#836 BUG: set column name when using `xorbits.pandas.Index`
  python/xorbits/_mars/dataframe/datasource/index.py
  python/xorbits/core/tests/test_execution.py
Labels: bug

#837 ENH: upgrade CI tests to python>=3.10
  .github/workflows/python.yaml
  python/xorbits/_mars/lib/sparse/tests/test_sparse.py
  python/xorbits/_mars/services/scheduling/supervisor/tests/test_assigner.py
  python/xorbits/_mars/services/scheduling/supervisor/tests/test_globalresource.py
  python/xorbits/_mars/services/scheduling/supervisor/tests/test_queue_balance.py
  python/xorbits/_mars/tensor/arithmetic/tests/test_arithmetic_execution.py
  python/xorbits/_mars/tensor/core.py
  python/xorbits/_mars/tensor/indexing/tests/test_indexing_execution.py
  python/xorbits/_mars/tensor/linalg/tests/test_linalg_execution.py
  python/xorbits/_mars/tensor/merge/tests/test_merge_execution.py
  python/xorbits/_mars/tensor/reduction/tests/test_reduction_execution.py
  python/xorbits/_mars/tensor/statistics/histogram.py
  python/xorbits/_mars/tensor/tests/test_utils.py
  python/xorbits/_mars/tensor/utils.py
Labels: enhancement

#838 DOC: operator fusion
  doc/source/getting_started/installation.rst
  doc/source/user_guide/best_practices.rst
  doc/source/user_guide/operator_fusion.rst
Labels: documentation
