Repository xorbitsai/xorbits, pull requests merged in 2024-11, with the labels that each got.

#825 BLD: Support python 3.12
  .github/workflows/build-wheel.yaml
  .github/workflows/python.yaml
  CI/requirements-wheel.txt
  CI/test_basic_execution.py
  python/pyproject.toml
  python/xorbits/_mars/_utils.pyx
  python/xorbits/_mars/contrib/dask/tests/test_dask.py
  python/xorbits/_mars/storage/tests/test_libs.py
  python/xorbits/_mars/tensor/base/moveaxis.py
  python/xorbits/_mars/tensor/lib/index_tricks.py
  python/xorbits/_mars/utils.py
Labels: build

#826 BLD: Compat with numpy 2.x
  .github/workflows/asv.yaml
  asv/asv.conf.json
  doc/source/getting_started/installation.rst
  python/pyproject.toml
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#788 ENH: Fix cuda storage transfer deadlock on multiple GPUs
  python/setup.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/services/storage/handler.py
  python/xorbits/_mars/services/storage/tests/test_transfer.py
  python/xorbits/_mars/services/storage/tests/test_transfer_gpu.py
  python/xorbits/_mars/services/storage/transfer.py
Labels: enhancement, gpu

#827 BUG: fix xoscar.errors.NoIdleSlot when using new_cluster
  python/xorbits/_mars/deploy/oscar/local.py
Labels: bug, gpu

#831 BLD: Dockerfile for cpu and cuda
  .github/workflows/docker-cd.yaml
  .github/workflows/python.yaml
  doc/source/development/contributing_environment.rst
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_kubernetes.po
  doc/source/user_guide/deployment_kubernetes.rst
  doc/source/user_guide/storage_backend.rst
  python/xorbits/deploy/docker/Dockerfile.base
  python/xorbits/deploy/docker/Dockerfile.cpu
  python/xorbits/deploy/docker/Dockerfile.cpu.base
  python/xorbits/deploy/docker/Dockerfile.cuda
  python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
Labels: build, gpu
