Repository xorbitsai/xorbits, pull requests merged in 2024-09, with the labels that each got.

#806 TST: Fix cudf & hadoop failed tests cases
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/datasource/index.py
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/merge/concat.py
  python/xorbits/_mars/dataframe/merge/merge.py
  python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
Labels: testing, gpu

#805 ENH: distributed xgboost.init with rabit deprecated, move to collective
  python/xorbits/_mars/learn/contrib/xgboost/tracker.py
  python/xorbits/_mars/learn/contrib/xgboost/train.py
Labels: enhancement

#809 DOC: update doc content && update sphinx to latest version
  doc/source/conf.py
  doc/source/getting_started/index.rst
  doc/source/index.rst
  doc/source/libraries/index.rst
  doc/source/libraries/xorbits_data/pandas.rst
  doc/source/libraries/xorbits_inference/index.rst
  doc/source/reference/datasets/index.rst
  doc/source/reference/index.rst
  doc/source/reference/lightgbm/learning.rst
  doc/source/reference/lightgbm/sklearn.rst
  doc/source/reference/xgboost/learning_api.rst
  doc/source/reference/xgboost/sklearn.rst
  doc/source/user_guide/deployment_cluster.rst
  doc/source/user_guide/deployment_slurm.rst
  doc/source/user_guide/loading_data.rst
  python/setup.cfg
Labels: documentation

#804 ENH: Fix some warning caused by deprecation
  .github/workflows/asv.yaml
  .github/workflows/python.yaml
  python/xorbits/_mars/_utils.pyx
  python/xorbits/_mars/dataframe/base/accessor.py
  python/xorbits/_mars/dataframe/base/apply.py
  python/xorbits/_mars/dataframe/base/tests/test_apply_execution.py
  python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/indexing/index_lib.py
  python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
  python/xorbits/_mars/dataframe/missing/fillna.py
  python/xorbits/_mars/dataframe/missing/tests/test_missing_execution.py
Labels: enhancement

#814 DOC: update CI environment dependencies for doc build
  .github/workflows/python.yaml
  python/xorbits/lightgbm/__init__.py
  python/xorbits/lightgbm/mars_adapters/core.py
Labels: documentation

#815 ENH: update web packages version
  .github/workflows/build-wheel.yaml
  python/xorbits/web/ui/package-lock.json
  python/xorbits/web/ui/package.json
Labels: enhancement

#816 DOC: Add storage backend, fix broken links, update API reference
  .github/ISSUE_TEMPLATE/other.md
  .github/workflows/python.yaml
  README.md
  doc/source/development/contributing_documentation.rst
  doc/source/development/contributing_environment.rst
  doc/source/index.rst
  doc/source/libraries/xorbits_data/index.rst
  doc/source/libraries/xorbits_data/numpy.rst
  doc/source/libraries/xorbits_inference/index.rst
  doc/source/libraries/xorbits_train/index.rst
  doc/source/libraries/xorbits_tune/index.rst
  doc/source/reference/index.rst
  doc/source/reference/lightgbm/learning.rst
  doc/source/reference/lightgbm/sklearn.rst
  doc/source/user_guide/best_practices.rst
  doc/source/user_guide/index.rst
  doc/source/user_guide/loading_data.rst
  doc/source/user_guide/storage_backend.rst
  python/setup.cfg
  python/xorbits/_mars/deploy/oscar/cmdline.py
  python/xorbits/_mars/deploy/oscar/tests/test_cmdline.py
  python/xorbits/_mars/deploy/oscar/worker.py
  python/xorbits/_mars/deploy/tests/test_utils.py
  python/xorbits/_mars/deploy/utils.py
  python/xorbits/_mars/deploy/yarn/config.py
  python/xorbits/_mars/deploy/yarn/tests/test_config.py
  python/xorbits/_mars/storage/filesystem.py
  python/xorbits/_mars/storage/tests/test_libs.py
  python/xorbits/_mars/utils.py
  python/xorbits/deploy/__init__.py
  python/xorbits/deploy/kubernetes/config.py
  python/xorbits/deploy/kubernetes/tests/test_config.py
Labels: documentation
