Repository xorbitsai/xorbits, pull requests merged in 2024-10, with the labels that each got.

#818 ENH: Fix config for xorbits and xorbits.pandas
  doc/source/reference/xorbits/index.rst
  doc/source/user_guide/best_practices.rst
  doc/source/user_guide/chunking.rst
  doc/source/user_guide/configuration.rst
  doc/source/user_guide/deployment_cluster.rst
  doc/source/user_guide/index.rst
  python/xorbits/__init__.py
  python/xorbits/_mars/config.py
  python/xorbits/_mars/tests/test_config.py
  python/xorbits/config.py
  python/xorbits/pandas/_config/config.py
  python/xorbits/pandas/_config/test/test_config.py
Labels: enhancement

#819 DOC: installation and compatible packages
  doc/source/getting_started/installation.rst
Labels: documentation

#820 BLD: Fix upload PyPI
  .github/workflows/build-wheel.yaml
Labels: build

#822 DOC: URLs link to original lightgbm and xgboost docs
  doc/source/reference/index.rst
  doc/source/reference/lightgbm/learning.rst
  doc/source/reference/lightgbm/sklearn.rst
  doc/source/reference/xgboost/core.rst
  doc/source/reference/xgboost/learning_api.rst
  doc/source/reference/xgboost/sklearn.rst
Labels: documentation

#817 ENH: Compatible with NumPy 2.x
  .github/workflows/python.yaml
  doc/source/user_guide/storage_backend.rst
  python/setup.cfg
  python/xorbits/_mars/core/operand/core.py
  python/xorbits/_mars/dataframe/indexing/align.py
  python/xorbits/_mars/dataframe/missing/tests/test_missing.py
  python/xorbits/_mars/dataframe/reduction/core.py
  python/xorbits/_mars/dataframe/statistics/corr.py
  python/xorbits/_mars/learn/contrib/lightgbm/_predict.py
  python/xorbits/_mars/learn/decomposition/tests/test_truncated_svd.py
  python/xorbits/_mars/learn/utils/validation.py
  python/xorbits/_mars/tensor/__init__.py
  python/xorbits/_mars/tensor/arithmetic/tests/test_arithmetic.py
  python/xorbits/_mars/tensor/array_utils.py
  python/xorbits/_mars/tensor/base/broadcast_to.py
  python/xorbits/_mars/tensor/base/expand_dims.py
  python/xorbits/_mars/tensor/base/rollaxis.py
  python/xorbits/_mars/tensor/base/tests/test_base.py
  python/xorbits/_mars/tensor/base/tests/test_base_execution.py
  python/xorbits/_mars/tensor/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/tensor/fft/fft.py
  python/xorbits/_mars/tensor/fft/fft2.py
  python/xorbits/_mars/tensor/fft/fftn.py
  python/xorbits/_mars/tensor/fft/hfft.py
  python/xorbits/_mars/tensor/fft/ifft.py
  python/xorbits/_mars/tensor/fft/ifft2.py
  python/xorbits/_mars/tensor/fft/ifftn.py
  python/xorbits/_mars/tensor/fft/ihfft.py
  python/xorbits/_mars/tensor/fft/irfft.py
  python/xorbits/_mars/tensor/fft/irfft2.py
  python/xorbits/_mars/tensor/fft/irfftn.py
  python/xorbits/_mars/tensor/fft/rfft.py
  python/xorbits/_mars/tensor/fft/rfft2.py
  python/xorbits/_mars/tensor/fft/rfftn.py
  python/xorbits/_mars/tensor/indexing/compress.py
  python/xorbits/_mars/tensor/indexing/tests/test_indexing_execution.py
  python/xorbits/_mars/tensor/lib/index_tricks.py
  python/xorbits/_mars/tensor/linalg/norm.py
  python/xorbits/_mars/tensor/merge/stack.py
  python/xorbits/_mars/tensor/merge/tests/test_merge.py
  python/xorbits/_mars/tensor/random/permutation.py
  python/xorbits/_mars/tensor/random/tests/test_random.py
  python/xorbits/_mars/tensor/reduction/core.py
  python/xorbits/_mars/tensor/reduction/tests/test_reduction.py
  python/xorbits/_mars/tensor/reduction/tests/test_reduction_execution.py
  python/xorbits/_mars/tensor/spatial/distance/squareform.py
  python/xorbits/_mars/tensor/utils.py
  python/xorbits/_mars/tests/test_session.py
  python/xorbits/numpy/__init__.py
  python/xorbits/numpy/lib/index_tricks.py
  python/xorbits/numpy/mars_adapters/tests/test_numpy_examples.py
  python/xorbits/utils.py
Labels: enhancement

#824 DOC: URLs link to original numpy and pandas docs
  .github/workflows/python.yaml
  doc/source/conf.py
  doc/source/reference/index.rst
  doc/source/reference/lightgbm/learning.rst
  doc/source/reference/lightgbm/sklearn.rst
  doc/source/reference/numpy/array-creation.rst
  doc/source/reference/numpy/array-manipulation.rst
  doc/source/reference/numpy/bitwise.rst
  doc/source/reference/numpy/fft.rst
  doc/source/reference/numpy/indexing.rst
  doc/source/reference/numpy/io.rst
  doc/source/reference/numpy/linalg.rst
  doc/source/reference/numpy/logic.rst
  doc/source/reference/numpy/math.rst
  doc/source/reference/numpy/random.rst
  doc/source/reference/numpy/set.rst
  doc/source/reference/numpy/sort.rst
  doc/source/reference/numpy/statistics.rst
  doc/source/reference/pandas/frame.rst
  doc/source/reference/pandas/general_functions.rst
  doc/source/reference/pandas/groupby.rst
  doc/source/reference/pandas/index.rst
  doc/source/reference/pandas/indexing.rst
  doc/source/reference/pandas/io.rst
  doc/source/reference/pandas/series.rst
  doc/source/reference/pandas/window.rst
  doc/source/reference/xgboost/learning_api.rst
  doc/source/reference/xgboost/sklearn.rst
Labels: documentation
