Repository xorbitsai/xorbits, pull requests merged in 2024-08, with the labels that each got.

#794 ENH: Fix tests hang in CI
  .github/workflows/python.yaml
  python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
  python/xorbits/_mars/dataframe/reduction/aggregation.py
  python/xorbits/_mars/dataframe/reduction/core.py
  python/xorbits/_mars/lib/groupby_wrapper.py
  python/xorbits/_mars/storage/cuda.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
Labels: enhancement

#796 BLD: Fix Docker CI/CD workflow
  python/xorbits/deploy/docker/Dockerfile.base
Labels: build

#798 ENH: support cudf Buffer BufferOwner structure
  python/xorbits/_mars/_utils.pyx
Labels: enhancement, gpu

#793 ENH: Fix DataFrame._data deprecated warnings
  CI/test_basic_execution.py
  python/xorbits/_mars/_utils.pyx
Labels: enhancement

#797 REF: Delede code on pd < 1.2.2
  python/xorbits/_mars/dataframe/base/transform.py
  python/xorbits/_mars/dataframe/indexing/reindex.py
  python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
  python/xorbits/_mars/dataframe/window/rolling/aggregation.py
  python/xorbits/_mars/lib/groupby_wrapper.py
  python/xorbits/_mars/utils.py
Labels: refactor

#801 BLD: Fix slurm CI/CD workflow
  CI/slurm/Dockerfile
  CI/slurm/docker-compose.yml
  CI/slurm/register_cluster.sh
  CI/slurm/slurm.sh
  CI/slurm/start-slurm.sh
Labels: build

#799 ENH: Fix gpu cudf `to_csv`
  python/xorbits/_mars/dataframe/datastore/tests/test_datastore.py
  python/xorbits/_mars/dataframe/datastore/tests/test_datastore_execution.py
  python/xorbits/_mars/dataframe/datastore/to_csv.py
Labels: enhancement, gpu

#802 BLD: update CI test workflow yaml
  .github/workflows/python.yaml
Labels: build

#783 ENH: Fix vineyard compatibility issue
  .github/workflows/python.yaml
  .gitignore
  python/xorbits/_mars/storage/vineyard.py
Labels: enhancement

#792 BLD: Fix asv workflow
  .github/workflows/asv.yaml
  asv/asv.conf.json
Labels: build

#803 ENH: fix cudf comp issue
  python/xorbits/_mars/_utils.pyx
  python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
Labels: enhancement, gpu
