Repository xorbitsai/xorbits, pull requests merged in 2024-06, with the labels that each got.

#772 ENH: fix test CI dependency of hadoop, lightgbm and web ui
  .github/workflows/python.yaml
  .pre-commit-config.yaml
  CI/install-hadoop.sh
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_hdfs.py
  python/xorbits/_mars/dataframe/datastore/tests/test_datastore_hdfs.py
  python/xorbits/numpy/numpy_adapters/core.py
  python/xorbits/web/ui/package-lock.json
  python/xorbits/web/ui/package.json
Labels: enhancement

#775 TST: compatible libs with pandas 1.5.3
  .github/workflows/python.yaml
Labels: testing

#776 BUG: fix compatibility issue of df.sort_index() and df.groupby(sort=True)
  python/xorbits/_mars/dataframe/groupby/sort.py
  python/xorbits/_mars/dataframe/sort/sort_index.py
  python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
Labels: bug

#779 ENH: Remove `sum_over_features` parameter from `manhattan_distances` with sklearn > 1.4
  python/xorbits/_mars/learn/metrics/pairwise/manhattan.py
  python/xorbits/_mars/learn/metrics/pairwise/tests/test_manhattan_distances.py
Labels: enhancement

#777 BUG: fix CI of pypi & dockerhub
  .github/workflows/build-wheel.yaml
  .github/workflows/docker-cd.yaml
  CI/requirements-wheel.txt
  python/xorbits/deploy/docker/Dockerfile.base
Labels: bug

#784 BLD: Fix macos and windows build CI
  .github/workflows/build-wheel.yaml
  CI/requirements-wheel.txt
Labels: build
