Repository xorbitsai/xorbits, pull requests merged in 2025-02, with the labels that each got.

#844 BLD: Fix pyarrow & alluxio CI errors
  .github/workflows/python.yaml
  CI/requirements-wheel.txt
  asv/benchmarks/learn/metrics.py
  python/pyproject.toml
Labels: build

#843 ENH: Update pandas read_* funcions of `dtype_backend` param with pyarrow
  .github/workflows/python.yaml
  benchmarks/tpch/README.md
  benchmarks/tpch/run_queries.py
  python/xorbits/_mars/config.py
  python/xorbits/_mars/dataframe/datasource/read_csv.py
  python/xorbits/_mars/dataframe/datasource/read_parquet.py
  python/xorbits/_mars/dataframe/datasource/read_sql.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
  python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
  python/xorbits/_mars/dataframe/reduction/nunique.py
  python/xorbits/_mars/learn/contrib/lightgbm/tests/test_classifier.py
  python/xorbits/_mars/learn/contrib/xgboost/tests/test_classifier.py
  python/xorbits/lightgbm/tests/test_classifier.py
Labels: enhancement

#846 BUG: Fix XGBoost/LightGBM test execution and scikit-learn compatibility
  .github/workflows/python.yaml
  python/xorbits/_mars/learn/preprocessing/_data.py
  python/xorbits/_mars/learn/utils/tests/test_validation.py
  python/xorbits/_mars/learn/utils/validation.py
  python/xorbits/_mars/utils.py
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
Labels: bug

#847 BLD: upload pypi CI pipeline
  .github/workflows/asv.yaml
  .github/workflows/build-wheel.yaml
  .github/workflows/docker-cd.yaml
  .github/workflows/python.yaml
  python/setup.cfg
Labels: build

#848 ENH: remove unreachable constructors wrappers from `xorbits.pandas` & remove `lhoestq/test` huggingface repo in datasets test
  python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
  python/xorbits/pandas/mars_adapters/core.py
Labels: enhancement
